apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: roundabout
      port: 9000
      server: clickhouse
      username: default
      tlsSkipVerify: false
    secureJsonData:
      password: ''
    isDefault: true
    editable: true
